export const CAR_MODELS: Record<string, string[]> = {
  // Китайские бренды
  "Avatr": ["11", "12", "07"],
  "BYD": ["Han", "Tang", "Song Plus", "Seal", "Dolphin", "Atto 3", "Yuan Plus", "Qin Plus", "Frigate 07", "Destroyer 05", "Seagull", "Leopard 5", "Yangwang U8"],
  "Changan": ["UNI-K", "UNI-T", "UNI-V", "CS35 Plus", "CS55 Plus", "CS75 Plus", "CS85 Coupe", "CS95", "Alsvin", "Eado Plus", "Hunter Plus", "Lamore"],
  "Chery": ["Tiggo 4 Pro", "Tiggo 7 Pro", "Tiggo 7 Pro Max", "Tiggo 8", "Tiggo 8 Pro", "Tiggo 8 Pro Max", "Arrizo 8"],
  "Dongfeng": ["Shine Max", "Aeolus", "Captain-T", "M-Hero 917", "Oting Paladin", "DF 6", "580", "Rich 6"],
  "Exeed": ["LX", "TXL", "VX", "RX"],
  "FAW": ["Bestune T77", "Bestune T55", "Bestune B70", "Bestune NAT"],
  "GAC": ["GS5", "GS8", "M8", "Empow", "Emkoo"],
  "Geely": ["Coolray", "Atlas", "Atlas Pro", "Tugella", "Monjaro", "Emgrand", "Preface", "Okavango", "Belgee X50", "Belgee X70", "Galaxy L7"],
  "Great Wall": ["Poer", "Poer KingKong", "Wingle 7", "Cannon", "Hover"],
  "Haval": ["Jolion", "F7", "F7x", "Dargo", "Dargo X", "H9", "M6", "H6"],
  "Hongqi": ["H5", "H9", "HS5", "HS7", "E-HS9", "HQ9"],
  "Jetour": ["Dashing", "X70 Plus", "X90 Plus", "T2"],
  "Li Auto": ["L7", "L8", "L9", "MEGA"],
  "Lynk & Co": ["01", "03", "05", "08", "09", "Z10"],
  "Nio": ["ES6", "ES7", "ES8", "ET5", "ET7", "EC6", "EC7"],
  "Omoda": ["C5", "S5", "S5 GT"],
  "Tank": ["300", "400", "500", "700"],
  "Voyah": ["Free", "Dream", "Passion"],
  "Xpeng": ["G3", "G6", "G9", "P5", "P7", "X9"],
  "Zeekr": ["001", "009", "X", "007", "7X"],

  // Европейские бренды
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "Brera", "159", "Mito", "Giulietta"],
  "Aston Martin": ["DBX", "Vantage", "DB11", "DB12", "DBS", "Rapide"],
  "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q5", "Q7", "Q8", "e-tron", "TT", "R8", "RS3", "RS4", "RS5", "RS6", "RS7", "RS Q8"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z4", "i3", "i4", "iX", "M2", "M3", "M4", "M5", "M8"],
  "Citroën": ["C3", "C4", "C5 Aircross", "Berlingo", "Jumper", "SpaceTourer", "C-Elysee"],
  "Dacia": ["Duster", "Sandero", "Logan", "Jogger", "Spring"],
  "Ferrari": ["296 GTB", "812 Superfast", "F8 Tributo", "Purosangue", "Roma", "SF90 Stradale", "Portofino"],
  "Fiat": ["500", "500X", "500L", "Panda", "Tipo", "Ducato", "Doblo", "Albea", "Punto"],
  "Jaguar": ["E-Pace", "F-Pace", "I-Pace", "F-Type", "XE", "XF", "XJ"],
  "Lamborghini": ["Aventador", "Huracan", "Urus", "Revuelto", "Gallardo"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar", "Freelander"],
  "Maserati": ["Ghibli", "Levante", "Quattroporte", "Grecale", "MC20", "GranTurismo"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "E-Class", "S-Class", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "CLA", "CLS", "EQA", "EQB", "EQC", "EQE", "EQS", "V-Class", "Sprinter", "Vito", "Maybach S-Class", "Maybach GLS"],
  "Mini": ["Cooper", "Clubman", "Countryman", "Paceman", "Cabrio"],
  "Opel": ["Astra", "Corsa", "Crossland", "Grandland", "Mokka", "Insignia", "Zafira", "Vivaro", "Combo"],
  "Peugeot": ["208", "308", "408", "508", "2008", "3008", "5008", "Partner", "Traveller", "Boxer", "Expert"],
  "Porsche": ["911", "Boxster", "Cayman", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Renault": ["Arkana", "Captur", "Clio", "Duster", "Kaptur", "Koleos", "Logan", "Megane", "Sandero", "Kangoo", "Master", "Trafic", "Fluence"],
  "Rolls-Royce": ["Cullinan", "Ghost", "Phantom", "Spectre", "Wraith", "Dawn"],
  "Seat": ["Arona", "Ateca", "Ibiza", "Leon", "Tarraco", "Altea"],
  "Skoda": ["Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Rapid", "Superb", "Enyaq", "Yeti", "Roomster"],
  "Volkswagen": ["Amarok", "Arteon", "Caddy", "Golf", "Jetta", "Multivan", "Passat", "Polo", "Taos", "Teramont", "Tiguan", "Touareg", "Transporter", "ID.3", "ID.4", "ID.6", "ID.7", "Caravelle", "Crafter"],
  "Volvo": ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "C40", "EX30", "EX90"]
};
